FROM node:20 AS build 

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY .env.local .env

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g", "daemon","off;"]