apiVersion: apps/v1
kind: Deployment
metadata:
  name: forever-admin
  namespace: forever
  labels:
    app: forever-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forever-admin
  template:
    metadata:
      labels:
        app: forever-admin
    spec:
      containers:
        - name: admin
          image: samarraghav1/forever-admin:8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          envFrom:
            - configMapRef:
                name: admin-config
---
apiVersion: v1
kind: Service
metadata:
  name: forever-admin
  namespace: forever
spec:
  selector:
    app: forever-admin
  ports:
    - port: 4002
      targetPort: 80
