apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forever
resources:
  - 00-namespace-config.yaml
  - 10-admin.yaml
  - 20-frontend.yaml
  - 30-backend.yaml
  - 40-database.yaml
  - 50-ingress.yaml
